const AllData = [
    {
        "packId": 1,
        "packageName": "Hampta Pass",
        "region": "Himalayan",
        "altitude": "14000 ft",
        "grade": "Medium",
        "duration": "6 Days",
        "season": "Winter",
        "trekkingKm": "25 km",
        "ageLimit": "12 years",
        "hotelFacility": "Available",
        "stay": "Camping & Hotel",
        "nearbyPlaces": "Manali, Kullu",
        "trail": "Trail through mountain",
        "train": "Joginder Nagar",
        "airport": "Bhuntar, Manali",
        "telephoneAvailable": "Available",
        "price": 15000,
        "description": "Hampta Pass is a beautiful crossover trek that spreads across the lush green valleys of Kullu-Manali to the arid and barren landscapes of Chandra Valley in Lahaul. This trek presents the amalgamation of distinct landscapes and cultures, which is a unique experience in itself. The trek entwines along rocky paths, grasslands, gushing streams, cascading waterfalls, hanging glaciers, and the beautiful crescent-shaped emerald lake ‘Chandratal’. Get to witness the confluence of three passes, Hampta Pass, Rohtang Pass, and Spiti, which is quite a surreal experience and not to mention a close encounter with the Buddhist culture and the lifestyle in the remote Himalayan villages. The inhabitants of Sethan are originally migrants from Tibet and Spiti Valley and you will get to observe their distinct culture and traditions.",
        "image": "pack1",
        "startingDate": "2023-07-02"

    },


    {
        "packId": 2,
        "packageName": "Bhrigu Lake Trek",
        "region": "Himalayan",
        "altitude": "12590 ft",
        "grade": "Medium",
        "duration": "4 Days",
        "season": "Winter",
        "trekkingKm": "17 km",
        "ageLimit": "12 years",
        "hotelFacility": "Available",
        "stay": "Camping & Hotel",
        "nearbyPlaces": "Manali, Kullu",
        "trail": "Lake Trek",
        "train": "Joginder Nagar",
        "airport": "Bhuntar, Manali",
        "telephoneAvailable": "Available",
        "price": 12000,
        "description": "Bhrigu Lake is a high-altitude glacial lake located in the upper Kullu Valley on the eastern side of the popular Rohtang Pass in Himachal Pradesh.An ideal trekking opportunity for both beginners and seasoned trekkers as well as families, the Bhrigu Lake trek is full of nature’s wonders.Perched atop an altitude of 14, 000 ft, this trek offers stunning views of the alpine meadows and grasslands and you will catch glimpses of the seven sister peaks.The panoramic view of the snow - capped mountains and their reflections on the lake offers ample opportunities for the shutterbugs to capture nature in its full glory.The trek history is steeped in mythology.It is believed that the famous saint Maharishi Bhrigu used to meditate near the lake.The Lake is not the only major attraction in the trek but the beautiful grasslands that cover the valley are a treat of their own.Walk through tree covers and a moderately steep climb to enter into the grasslands and soon you will be left smitten at all the 		beauty that lies all around you.",
        "image": "pack1",
        "startingDate": "2023-08-07",

    },

    {
        "packId": 3,
        "packageName": "Kheerganga Trek",
        "region": "Himalayan",
        "altitude": "9700 ft",
        "grade": "Easy",
        "duration": "2 Days",
        "season": "Winter",
        "trekkingKm": "14 km",
        "ageLimit": "10 years",
        "hotelFacility": "Available",
        "stay": "Camping & Hotel",
        "nearbyPlaces": "Barshaini",
        "trail": "Trail through mountain",
        "train": "Joginder Nagar",
        "airport": "Bhuntar, Manali",
        "telephoneAvailable": "Available",
        "price": 8000,
        "description": "The name Kheerganga is derived from a legend that states the Keerganga springs were once filled with rice puddings provided by Lord Shiva. Kheerganga’s history is rich and has profound religious significance both to Hindus and Sikh’s. According to a popular local folklore, after losing the great race against Lord Ganesha, Lord Kartikey decided to seclude himself and meditate in these hills. Thousands of years passed, but all attempts to reach Lord Kartikey failed, so Lord Shiva decided to take on the task himself, forming a stream of kheer (rice pudding) to bring Lord Kartikey back. This trek offers a great opportunity to explore the local people and their cuisines. The camping site of this trek provides a majestic view of the great snowcapped peaks. While trekking amidst Barshini, trekkers can witness the beautiful the Parvati River that gorges from Barshaini and also flows adjacent to the village.",
        "image": "pack1",
        "startingDate": "2023-07-13"

    },

    {
        "packId": 4,
        "packageName": "Sar Pass Trek",
        "region": "Himalayan",
        "startingDate": "2023-05-22",
        "altitude": "13800 ft",
        "grade": "Medium",
        "duration": "8 Days",
        "season": "Summer",
        "trekkingKm": "40 km",
        "ageLimit": "14 years",
        "hotelFacility": "Available",
        "stay": "Camping & Hotel",
        "nearbyPlaces": "Barshaini",
        "trail": "Trail through mountain",
        "train": "Pathankot",
        "airport": "Bhuntar, Manali",
        "telephoneAvailable": "Available",
        "price": 18000,
        "description": "Sar Pass Trek will let you, the traveller, experience it all, starting from trekking through forests of pine and groves of rhododendrons, to camping in the high-altitude Grahan Village. The trek allows the takers to witness the Himalayas covered in lush greens and pristine white in Kasol, a small village perched at the height of 1580m in Parvati Valley, located in the Kullu. The Sar Pass trek is gaining popularity as a favourite amongst those seeking adventure in Kasol or Kullu. ",
        "image": "pack1",
        "startingDate": "2023-05-22"

    },

    {
        "packId": 5,
        "packageName": "Chandratal Lake Trek",
        "region": "Himalayan",
        "altitude": "13950 ft",
        "grade": "Medium",
        "duration": "10 Days",
        "season": "Summer",
        "trekkingKm": "50 km",
        "ageLimit": "14 years",
        "hotelFacility": "Available",
        "stay": "Camping & Hotel",
        "nearbyPlaces": "Spiti Valley",
        "trail": "Lake Trek",
        "train": "Joginder Nagar",
        "airport": "Bhuntar, Manali",
        "telephoneAvailable": "Available",
        "price": 20000,
        "description": "Chandratal Trek is the most famous and popular lake in the Lahaul and Spiti Range, the turquoise blue lake is a hidden gem also situated in the Chandrabhaga Range. It’s a terrific attraction for all the tourist trekkers and adventurers.It is 14 km away from Batal. The routes are extremely treacherous, but worth it as you will get to witness the vistas of nature. Chandratal is a tourist destination for trekkers and campers. The lake is accessible on foot from Batal as well as from the Kunzum Pass from May to late October.",
        "image": "pack1",
        "startingDate": "2023-08-10"

    },

    {
        "packId": 6,
        "packageName": "Nilgiri Green Lake",
        "region": "South_India",
        "altitude": "1437 ft",
        "grade": "Easy",
        "duration": "5 Days",
        "season": "Rainy",
        "trekkingKm": "12 KM",
        "ageLimit": "12 Years",
        "hotelFacility": "Available",
        "stay": "Camping & Hotel",
        "nearbyPaces": "Madhumalai National Park",
        "trail": "Through forest",
        "train": "Ooty Station",
        "airport": "Ozar airport",
        "telephoneAvailable": "Available",
        "price": 20000,
        "description": "Nilgiris is one of the most wanted spot for trekking when one is touring South India. With 24 peaks, Nilgiris is a part of Western Ghats and lies in the western end of Tamil Nadu. The picturesque beauty of Nilgiris fills the trekkers with enthusiasm, thrill and excitement. Various altitudes, terrain and distances comprises of a trek route to the Nilgiris. Nothing can be better than treeking Nilgiris from Ooty, Kotagiri and Coonoor. Ooty gives a trekker various routes which one can take and head towards the peak. The coffee plantations, orange grooves, tea gardens and pine trees make for the ideal ambiance to trek",
        "image": "pack1",
        "startingDate": "2023-05-04"
    },

    {
        "packId": 7,
        "packageName": "Baba Bhudangiri",
        "region": "South_India",
        "altitude": "6217 ft",
        "grade": "Medium",
        "duration": "5 Days",
        "season": "Rainy",
        "trekkingKm": "16 KM",
        "ageLimit": "15 Years",
        "hotelFacility": "Available",
        "stay": "Camping & Hotel",
        "nearbyPaces": "Baba Bhudangiri Temple",
        "trail": "Through hills and forest",
        "train": "Mangalore Station",
        "airport": "Mangalore airport",
        "telephoneAvailable": "Available",
        "price": 18000,
        "description": "Bababudangiri is an amazing trek in the mountains of Chikmagalur, located at a distance of 250 km from Bangalore, making it ideal for a weekend getaway. Starting on the hiking trail from Sarpadhari (alternatively from Attinagundi), you can see the peaks of Budangiri (1895 m) and Mullayanagiri (1930 m) looming at a distance. Together, the two mountains appear like a crescent moon, therefore known as the Chandra Drona Range",
        "image": "pack1",
        "startingDate": "2023-05-05"
    }
]

export default AllData;